import type { IntelEvent } from './types';

export const SAMPLE_EVENTS: IntelEvent[] = [
  {
    id: 'evt-001',
    title: 'PLA aircraft cross Taiwan Strait median line',
    summary:
      '4 J-16 fighters and 2 Y-9 EW aircraft tracked entering southwestern ADIZ. ROCAF scrambled CAP in response.',
    category: 'air',
    severity: 'medium',
    region: 'taiwan-strait',
    lat: 23.0,
    lon: 119.2,
    timestamp: new Date(Date.now() - 1000 * 60 * 35).toISOString(),
    source: 'Taiwan MND',
    sourceUrl: 'https://www.mnd.gov.tw/',
    tags: ['ADIZ', 'PLAAF', 'median-line'],
  },
  {
    id: 'evt-002',
    title: 'DPRK launches short-range ballistic missile toward East Sea',
    summary:
      'Single SRBM launched from Pyongan province; apogee ~50 km, range ~600 km. JCS confirms impact in EEZ.',
    category: 'missile',
    severity: 'high',
    region: 'korean-peninsula',
    lat: 39.55,
    lon: 127.5,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
    source: 'ROK JCS',
    sourceUrl: 'https://www.jcs.mil.kr/',
    tags: ['SRBM', 'DPRK', 'launch'],
  },
  {
    id: 'evt-003',
    title: 'PLAN carrier Shandong transits Bashi Channel',
    summary:
      'AIS-correlated escorts indicate Shandong carrier group southbound through Bashi Channel into Philippine Sea.',
    category: 'naval',
    severity: 'medium',
    region: 'taiwan-strait',
    lat: 21.0,
    lon: 121.5,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
    source: 'AIS / OSINT',
    tags: ['carrier', 'Shandong', 'PLAN'],
  },
  {
    id: 'evt-004',
    title: 'Thermal anomaly detected near Yongbyon complex',
    summary:
      'NASA FIRMS reports persistent thermal hotspot consistent with reactor operations. Awaiting commercial imagery confirmation.',
    category: 'satellite',
    severity: 'medium',
    region: 'korean-peninsula',
    lat: 39.79,
    lon: 125.76,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 14).toISOString(),
    source: 'NASA FIRMS',
    sourceUrl: 'https://firms.modaps.eosdis.nasa.gov/',
    tags: ['Yongbyon', 'thermal', 'reactor'],
  },
  {
    id: 'evt-005',
    title: 'Japan Coast Guard reports CCG incursion near Senkaku',
    summary:
      'Two China Coast Guard vessels enter 12 nm contiguous zone for ~3 hours. JCG patrol vessels shadowed and issued warnings.',
    category: 'naval',
    severity: 'low',
    region: 'other',
    lat: 25.74,
    lon: 123.47,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 20).toISOString(),
    source: 'Japan Coast Guard',
    tags: ['CCG', 'Senkaku', 'incursion'],
  },
  {
    id: 'evt-006',
    title: 'US-ROK combined aerial drill over Korean peninsula',
    summary:
      'USAF B-1B lancers flew with ROKAF F-35As and JASDF F-15Js in trilateral exercise over Yellow Sea.',
    category: 'air',
    severity: 'info',
    region: 'korean-peninsula',
    lat: 37.4,
    lon: 125.3,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 26).toISOString(),
    source: 'USFK / ROK MND',
    tags: ['B-1B', 'trilateral', 'exercise'],
  },
  {
    id: 'evt-007',
    title: 'Suspected cyber intrusion at Taiwan semiconductor supplier',
    summary:
      'TWCERT advisory cites APT41-linked tooling targeting tier-2 chip supplier; data exfiltration under investigation.',
    category: 'cyber',
    severity: 'medium',
    region: 'taiwan-strait',
    lat: 24.81,
    lon: 120.97,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 30).toISOString(),
    source: 'TWCERT',
    tags: ['APT41', 'semiconductor', 'cyber'],
  },
];
